name: publish pipeline

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish WebApi
        run: dotnet publish -c Release -o Publish
        working-directory: ./src/BookGenerator.WebApi
      - name: Publish WebAPP
        run: dotnet publish -c Release -o Publish
        working-directory: ./src/BookGenerator.Client
      - name: Deploy WebApi
        uses: azure/webapps-deploy@v2
        with:
          app-name: BookWriterApi
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_WEBAPI }}
          package: './src/BookGenerator.WebApi/Publish'
      - name: Deploy WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: BookWriter
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_WEBAPP }}
          package: './src/BookGenerator.Client/Publish'
        
