name: publish pipeline

on: [push]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.0
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish -c Release -o src/BookGenerator.Client/Publish --project src/BookGenerator.Client/BookGenerator.Client.csproj
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: BookGenerator
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '.src/BookGenerator.Client/Publish'
